baseURL = "http://example.org/"
languageCode = "en-us"
title = "sgillen's blog"
theme = "smol"
copyright = "Copyright 2021, Sean Gillen, All Rights Reserved"


# Parameters
[params]
     #  subtitle = "Subtitle"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "about.md"
        weight = 1 


# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/sgillen"
        weight = 1

        
